Repository truenas/py-libzfs, pull requests merged in 2022-01, with the labels that each got.

#159 NAS-114356 / 22.02 / Make sure we close opened snapshot handle
  libzfs.pyx
Labels: backport-13.0, jira

#158 NAS-114076 / 13.0 / Consider resilvering pool healthy, but add a warning yellow light
  libzfs.pyx
Labels: backport-22.02

#163 NAS-114503 / 22.02 / Free memory for snapshot mountpoint
  libzfs.pyx
Labels: jira

#167 NAS-114529 / 22.02 / Fix memory leak in py-libzfs iterators
  libzfs.pyx
Labels: backport-13.0, jira
